[package]
name = "physicsengine"
version = "0.1.0"
authors = ["alex <alex.gusain@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

nalgebra   = {version = "0.24.1", features = ["serde-serialize"] }
rapier3d = { version = "0.5.0", features = [ "serde-serialize", "wasm-bindgen" ] }

serde = { version = "1.0.123", features = ["derive"] }

rand = {version = "0.7.3", features = [ "wasm-bindgen" ] }

bincode = "1.3.2"



[lib]
crate-type = ["cdylib", "rlib"]