[package]
name = "physicsengine"
version = "0.1.0"
authors = ["alex <alex.gusain@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

nalgebra   = {version = "0.23.0", features = ["serde-serialize"] }
#ncollide3d = "*"
#nphysics3d = {version = "0.18", default-features = false, features = [ "dim3", "use-wasm-bindgen" ] }

rapier3d = { version = "0.4.2", features = [ "serde-serialize" ] }


serde = { version = "1.0.117", features = ["derive"] }

serde_json = "1.0.61"



rand = {version = "0.6.5", features = [ "wasm-bindgen" ] }



bincode = "1.3.1"
